name:               "Alok Kumar"
description:        "a blog by me"

url:                "alok760.github.io"
author:             "alok"
email:              "alok760@gmail.com"
gravatar_hash:      "b7d7e5732e2617042334196112cc1421"
twitter:            "alok760"
email:              "alok760@abc.com"
github:             "alok760"
pinterest:          "alok760"
linkedin:           "alok760"
facebook:           "alok760"

disqus_shortname:   "alok760-github-io"

background:         "http://apple.wallpapersfine.com/wallpapers/original/1242x2208/w-5273.jpg"

paginate:           5
paginate_path:      "/page:num/"

baseurl:            ""
permalink:          /:year/:month/:day/:title/

markdown:           kramdown

nav:
  - name:           "About"
    href:           "/about"
  - name:           "Download"
    href:           "/releases"

sass:
  style:            :compressed

defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"

gems:
  - jekyll-paginate
