# Site settings
title: Alok Kumar
description: Full stack web developer | Machine learning | Pythonista | cryptography | blockchain | network security | dev-ops
url: 'http://alok760.github.io'
baseurl: ''
# google_analytics: 'UA-XXXXXX-X'
# disqus_shortname: 'your-disqus-name'

author:
  name: 'Alok Kumar'
  email: alok760@gmail.com
  twitter_username: alok760
  facebook_username: alok760
  github_username:  alok760
  linkedin_username:  alok760

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

sass:
    sass_dir: _sass
    style: compressed

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

plugins: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
